language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
bundler_args: --jobs=3 --retry=2 --deployment --without development production
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'CREATE DATABASE sparkler_test;'
script: bundle exec rspec
