default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  username: root
  password: 
  socket: /tmp/postgres.sock

development:
  <<: *default
  database: sparkler_development

test:
  <<: *default
  database: sparkler_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sparkler_production
